### ISSUE TITLE
GBA build job is failing

### ISSUE THREAD

**Issue by ketsuban** [rust-lang-nursery/stdsimd#702]
@Lokathor alerted me earlier to [a build failure in the `gba` crate](https://travis-ci.org/rust-console/gba/builds/502888251) which appears to be caused by stdsimd code. Is this something we can solve on our end by a change to our [target specification](https://github.com/rust-console/gba/blob/master/thumbv4-none-agb.json), or does it require alterations to stdsimd?

**Comment by gnzlbg** [comment]
cc @japaric

**Comment by parched** [comment]
https://github.com/rust-lang-nursery/stdsimd/blob/f649570cb8d6b2ee56607418b07a00a8c7200f6e/crates/core_arch/src/acle/registers/aarch32.rs#L4

needs a `cfg(any(not(target_feature = thumb-mode), target_feature = v6t2))`

**Comment by Lokathor** [comment]
This was fixed, and we can close it now @gnzlbg

**Comment by gnzlbg** [comment]
The GBA build job is still failing, I'm repurposing this issue to track that.

**Comment by gnzlbg** [comment]
The error message is: 

```
error: Error loading target specification: Could not find specification for target "gba"
  |
  = help: Use `--print target-list` for a list of built-in targets
```

@Lokathor maybe you could look into that?

**Comment by Lokathor** [comment]
@gnzlbg I can look through this tomorrow, but just glancing at the failed build log I can say that the huge list of packages it was trying to build before it failed is never gonna build on gba, so i think the script got messed up a bit.

**Comment by gnzlbg** [comment]
Maybe it is trying to build everything using `--all`, you probably want to only build `crates/core_arch` and `crates/std_detect`.

**Comment by gnzlbg** [comment]
This has been fixed, thank you @Lokathor !
